apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: scrapzee
  namespace: argocd
spec:
  description: Scrapzee GitOps Project

  sourceRepos:
    - "https://github.com/Sagarrrsh/demo-scrap.git"

  destinations:
    - namespace: scrapzee
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    # Workloads
    - group: apps
      kind: Deployment

    # Core resources
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: PersistentVolumeClaim

    # Networking
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
