version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 15

  auth-service:
    build: ./auth-service
    image: scrapzee/auth-service:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:rootpassword@mysql:3306/scrapzee_auth
    ports:
      - "5001:5000"

  pricing-service:
    build: ./pricing-service
    image: scrapzee/pricing-service:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:rootpassword@mysql:3306/scrapzee_pricing
      AUTH_SERVICE_URL: http://auth-service:5000
    ports:
      - "5002:5000"

  user-service:
    build: ./user-service
    image: scrapzee/user-service:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:rootpassword@mysql:3306/scrapzee_users
    ports:
      - "5003:5000"

  dealer-service:
    build: ./dealer-service
    image: scrapzee/dealer-service:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:rootpassword@mysql:3306/scrapzee_dealer
    ports:
      - "5004:5000"

volumes:
  mysql-data:
